version: '3'

services:
  db:
    image: mysql:latest
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 9999
      MYSQL_DATABASE: adia_db
      MYSQL_PASSWORD: 9999
    ports:
      - "3000:3000"
#    expose:
#      - "3000"
#    command: --init-file init.sql
    volumes:
      - ./data/db:/var/lib/mysql